services:
  frontend:
    container_name: frontend-app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  
  backend:
    container_name: backend-typescript-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
     - .:/app
     - /app/node_modules